### ISSUE TITLE
Dynamic affix-bottom

### ISSUE THREAD

**Issue by septicmk** [wzpan/hexo-theme-wixo#10]
hello,我添加了disqus的代码,所以页面下会多出一块
![untitled](https://cloud.githubusercontent.com/assets/6965704/9136070/2c2cf7cc-3d46-11e5-9f7e-4b5aeb4a4f86.png)
也许我可以设置data-offset-bottom但是,评论框高度是会变的,我并不能写死.
如何动态的设置affix-bottom使得当这个toc滚动到评论区的时候能不再固定再页面上而是随文本一起滚上去呢.谢谢.

**Comment by wzpan** [comment]
Sorry，不知道为啥未能收到你的issue的邮件通知，所以我现在才看到这个issue。我更建议的做法是像我wiki那样把disqus的内容放在右侧区域里。例如[这篇文章](http://hahack.com/wiki/opencv-image.html#comments)

**Comment by septicmk** [comment]
谢谢, 我现在就是这样做的。
