### ISSUE TITLE
hexo g --silent 依然有输出...

### ISSUE THREAD

**Issue by nobystander** [wzpan/hexo-theme-wixo#12]
在执行`hexo g --silent` 后，终端依然会输出一些信息，目测是渲染文章的中间信息。
换别的主题没有类似输出。。。
本来没什么的，然而我渲染文章一多的时候会因为输出而严重拖慢速度 (100篇用了 22min

[输出信息](http://paste.ubuntu.com/14574445/)

**Comment by wzpan** [comment]
嗯，我忘记删掉一行调试信息了。现在已删除。请更新试试。

**Comment by nobystander** [comment]
也意识到应该是调试信息。。。已解决。
