### ISSUE TITLE
文章名字太长，会与右上角时间重叠

### ISSUE THREAD

**Issue by SWBetaWiKi** [wzpan/hexo-theme-wixo#14]
Joseph Pan：
　　你好！谢谢你提供的 Theme，很喜欢。在使用中，我发现，如果文章名字太长，会与右上角时间重叠，不知能否解决一下。这里是刚在 GitHub 上使用你的 wixo theme 建的博客：[swbetawiki](http://swbetawiki.github.io/2016/02/04/%E7%BA%AF%E5%B0%8F%E7%99%BD%E5%9C%A8GitHub%E4%B8%8A%E5%88%A9%E7%94%A8Git%E5%92%8CHexo%E6%90%AD%E5%BB%BA%E9%9D%99%E6%80%81%E5%8D%9A%E5%AE%A2/)

**Comment by wzpan** [comment]
这个恐怕没有很好的解决办法。除非我把时间信息挪到其他位置，不过我也找不到其他适合放时间的地方。我的建议是你尽可能控制字数，别把标题起的太长。

**Comment by SWBetaWiKi** [comment]
Roger that.
看样子只能这样了，谢谢。
