### ISSUE TITLE
Hi,正文侧边栏标题 如何修改

### ISSUE THREAD

**Issue by xxl6097** [wzpan/hexo-theme-wixo#15]
你的这个主题标题的生成必须是这条的语法
![image](https://cloud.githubusercontent.com/assets/8170647/15703016/b768778e-2815-11e6-8c1f-6158e5d9963e.png)

如何改成 # 标题

**Comment by wzpan** [comment]
你说的是希望在正文插入 H1 标题？不建议这么做，因为 H1 标题只用在文章标题中。正文的标题建议从二级标题 H2 ，即 ## 开始。

至于 

> ## 文本颜色 ##

和 

> ## 文本颜色

是等效的。都属于标准 Markdown 语法。

**Comment by wzpan** [comment]
问题应该已经解决。关闭本issue。如果问题，请重开。
