### ISSUE TITLE
是否考虑添加pjax

### ISSUE THREAD

**Issue by caisiduo** [wzpan/hexo-theme-wixo#16]

**Comment by wzpan** [comment]
能不能把需求描述清楚点呢？起码得告诉我：

1. pjax 是什么？
2. 为什么建议在 wixo 主题里添加 pjax ？

**Comment by caisiduo** [comment]
现在很多网站( facebook,  twitter)都支持这样的一种浏览方式， 当你点击一个站内的链接的时候， 不是做页面跳转， 而是只是站内页面刷新。 这样的用户体验， 比起整个页面都闪一下来说， 好很多。 其中有一个很重要的组成部分， 这些网站的ajax刷新是支持浏览器历史的， 刷新页面的同时， 浏览器地址栏位上面的地址也是会更改， 用浏览器的回退功能也能够回退到上一个页面。 那么如果我们想要实现这样的功能， 我们如何做呢？ 我发现pjax提供了一个脚本支持这样的功能。 pjax项目地址在  https://github.com/defunkt/jquery-pjax 。 实际的效果见：  http://pjax.heroku.com/ 没有勾选pjax的时候， 点击链接是跳转的。 勾选了之后， 链接都是变成了ajax刷新。

- 用户体验提升。

页面跳转的时候人眼需要对整个页面作重新识别， 刷新部分页面的时候， 只需要重新识别其中一块区域。自从我在自己的网站 GuruDigger 上面采用了pjax技术后， 不由觉得访问其他只有页面跳转的网站难受了许多。 同时， 由于刷新部分页面的时候提供了一个loading的提示， 以及在刷新的时候旧页面还是显示在浏览器中， 用户能够容忍更长的页面加载时间。

- 极大地减少带宽消耗和服务器消耗。

由于只是刷新部分页面， 大部分的请求（css/js）都不会重新获取， 网站带有用户登录信息的外框部分都不需要重新生成了。 虽然我没有具体统计这部分的消耗， 我估计至少有40%以上的请求， 30%以上的服务器消耗被节省了。
摘自《Pjax是什么以及为什么推荐大家用》

**Comment by wzpan** [comment]
这个需求可能超出了一个博客主题的要求，短期内暂不在计划中。欢迎 patch 。

**Comment by wzpan** [comment]
暂无支持这个特性的需求，关闭本issue。
