### ISSUE TITLE
是否开发一个生成你这个wiki页面的插件？

### ISSUE THREAD

**Issue by wbing-xu** [wzpan/hexo-theme-wixo#17]
因为你这个wiki是一整个hexo的主题的，而我想要在我的博客上（用的是另外的主题），嵌入你这样的一个wiki页面，而不用去维护两个hexo。
例如hexo-generator-douban这个插件吧，是可以生成一个豆瓣读书的页面，单独用来显示豆瓣读书的。
	
我所希望的是有一个比如叫hexo-generator-wiki的插件，我们可以先建一个目录，比如source/wiki/，专门去存放wiki文章来，然后运行该插件，生成一个wiki页面

这只是我一个想法而已~

**Comment by wzpan** [comment]
技术上难以实现
