### ISSUE TITLE
bug : SyntaxError: Unexpected token '<' in hexo-tag-bootstrap/input.js:8

### ISSUE THREAD

**Issue by YUbuntu0109** [wzpan/hexo-theme-wixo#24]
hey bro thanks for your works but it's throw a error as follows when I execute the command : `hexo clean or hexo g`, even though this bug did not directly lead to run the project unsuccessfully.

![image](https://user-images.githubusercontent.com/43493852/84223966-f1ed3280-ab0d-11ea-8ba1-86b26b10217c.png)

**Comment by wzpan** [comment]
Hi there. Can you try downgrade the hexo-tag-bootstrap to 0.0.8 and see whether it resolves the problem?

``` bash
npm uninstall hexo-tag-bootstrap
npm install hexo-tag-bootstrap@0.0.8
```

**Comment by GoogTech** [comment]
thanks bro i had fixed it and thanks your works again : https://anonymous.ishacker.net
