### ISSUE TITLE
目录显示有点问题

### ISSUE THREAD

**Issue by zhiyue** [wzpan/hexo-theme-wixo#6]
![](http://ww4.sinaimg.cn/large/8d6e2d38gw1eq3vxk5bebj20rp09oabx.jpg)

**Comment by wzpan** [comment]
没遇到过这个问题。能否把出问题的页面给我看下？我定位下原因。

**Comment by zhiyue** [comment]
http://wiki.printf.me/2015/03/12/Hexo%E5%86%99%E4%BD%9C%E5%B9%B3%E5%8F%B0%E6%90%AD%E5%BB%BA/

**Comment by wzpan** [comment]
找不到 responsive.css 。请确认 css 目录下有这个文件。

**Comment by zhiyue** [comment]
的确是少了responsive.css，加了之后可以正常显示。。但是hexo g 没有生成这个css

**Comment by zhiyue** [comment]
找到原因了，是我没有update主题。。

感谢作者，这个wiki主题很好用。。然后顺便问一下什么时候可以支持hexo3.0   :-D

**Comment by wzpan** [comment]
下周会做一次升级

**Comment by wzpan** [comment]
已升级
