### ISSUE TITLE
目录显示的问题

### ISSUE THREAD

**Issue by zhiyue** [wzpan/hexo-theme-wixo#8]
- 标题没加括号的情况下可以正常显示目录
![](http://ww2.sinaimg.cn/large/8d6e2d38gw1eroqcuh9uzj20yj0jw7b0.jpg)

- 标题里包含 "()" 或者 "/" 的字符时目录就会显示异常
![](http://ww1.sinaimg.cn/large/8d6e2d38gw1eroqenrwx6j20vo0hi79d.jpg)
![](http://ww4.sinaimg.cn/large/8d6e2d38gw1eroqfzrgq1j208a06k746.jpg)

**Comment by wzpan** [comment]
这个问题可能和 Bootstrap 的 scrollspy 有关。使用全角的括号 `（）` 可以解决这个问题。

**Comment by wzpan** [comment]
使用全角可以解决这个问题。关闭本issue。如有疑问请重开。
