### ISSUE TITLE
代码高亮显示部分异常

### ISSUE THREAD

**Issue by zhiyue** [wzpan/hexo-theme-wixo#9]
![](http://ww3.sinaimg.cn/large/8d6e2d38gw1esr3c5aq4dj20pn0fw75g.jpg)

hexo3.0.1

代码高亮异常。有部分语言不能正常高亮，行号也显示很异常

**Comment by zhiyue** [comment]
http://wiki.printf.me/2014/03/15/code-highlight/

**Comment by wzpan** [comment]
看了下 highlight.js 的 class reference ，不能高亮的代码应该是因为语言类型写错了。

* C# 应该是 "cs" 或 "csharp"；
* Assembler 应该是 “armasm” 或 “arm”。

改完应该可以解决。

**Comment by zhiyue** [comment]
:) OK 的确是这样。hexo 3.1.1要在highlight开启  auto_detect: true才自动自动检测语言
